### PR TITLE
Feature cpp library

### PR DESCRIPTION
**Pull request by sanine-a**
When working on a TSCK project, I realized that we didn't yet have a way to integrate Arduino communication with C++ programs, so I wrote a little library that does just that. It's been tested to work on Windows 10 and Debian Stretch. The syntax and usage is quite similar to the Arduino SerialController class. I've included an example file to look at. It depends on [libserialport](https://sigrok.org/wiki/Libserialport) which runs on pretty much anything we might throw it at (Windows, Mac, Linux, even Android and FreeBSD).

I'd appreciate if someone else would take a look at this!

### CODE REVIEW

**Comment by sanine-a** [comment]
This latest commit has been preliminarily tested to work on Windows 10 and Raspian 9.

**Comment by eojreyem** [comment]
I can't get example.cpp to compile. 
`#include <libserialport.h>   no such file or directory.`
I found this header file online here: https://github.com/mikepb/go-serial. But I can't figure out where to put it so that my compiler finds it.

**Comment by eojreyem** [comment]
So far I've copied SerialController.hpp from the other library folder into the example sketch folder to get the example sketch to compile.

Installed libserialport running this in linux terminal `sudo apt install libserialport-dev`

New problems
`Joe-Ubuntu$ g++ example.cpp 
/tmp/ccM5eaXv.o: In function `main':
example.cpp:(.text+0xa2): undefined reference to `ArduinoSerial::ArduinoSerial()'
example.cpp:(.text+0xb5): undefined reference to `ArduinoSerial::setDataCallback(void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >))'
example.cpp:(.text+0xd2): undefined reference to `ArduinoSerial::findMatchingPorts(int, int)'
example.cpp:(.text+0x116): undefined reference to `ArduinoSerial::openPort(sp_port*, int)'
example.cpp:(.text+0x131): undefined reference to `ArduinoSerial::update()'
example.cpp:(.text+0x1ea): undefined reference to `ArduinoSerial::~ArduinoSerial()'
example.cpp:(.text+0x222): undefined reference to `ArduinoSerial::~ArduinoSerial()'
collect2: error: ld returned 1 exit status
`

**Comment by sanine-a** [comment]
Since we are not likely to pursue C++ application development for the foreseeable future, does it make sense to close this pull request? I'm not sure that this library will see much, if any, use in the exhibit shop.

**Comment by brandonwkipp** [comment]
@sanine-a if you don't think this library will be useful in the shop, I'd think you'd be safe to close this one out.

**Pull request closed without merging**
